### ISSUE TITLE
Pertanyaan mengenai spek

### ISSUE THREAD

**Issue by girvinjunod** [gilliantuerah/BantuKurir-TSP#1]
> Aplikasi mampu menerima berkas eksternal lebih dari satu dan menampilkan semua jalur yang mungkin

Maksud dri spek ini apa ya kak, terutama bagian menampilkan semua jalur yang mungkin? Apakah lebih dari 1 berkas eksternal berarti lebih dari 1 pengiriman (satu perjalanan sampai balik lagi) atau digabungkan menjadi 1 pengiriman? Untuk menampilkan semua jalur yang mungkin, apakah maksudnya menampilkan semua kemungkinan jalur yang diambil dalam 1 pengiriman atau menampilkan jalur terpendek untuk tiap pengiriman? 

Juga ingin bertanya, apakah asumsinya itu setiap lokasi pasti ada jalur dengan semua lokasi yang lain?

**Comment by gilliantuerah** [comment]
Lebih dari 1 berkas eksternal maksudnya ada lebih dari 1 pengiriman yang perlu dicari jalur terpendeknya. Maksudnya menampilkan jalur terpendeki untuk tiap pengiriman ya. Iya bener asumsinya untuk setiap lokasi pasti ada jalur dengan semua lokasi lainnya

**Comment by girvinjunod** [comment]
Mau bertanya lagi kak
> Pengguna dapat memasukkan informasi pengiriman secara langsung dari website ataupun melalui berkas eksternal, yang terdiri atas:
Nama lokasi yang dituju (termasuk lokasi asal: Perusahaan)
Koordinat dari setiap lokasi
Identitas Kurir (nama)
Lokasi yang menjadi titik asal
Waktu pengiriman
Kecepatan rata-rata kurir

> Aplikasi mampu menampilkan jalur ter-efektif untuk melakukan pengiriman ke semua lokasi yang dimasukkan, dengan lokasi asal merupakan Perusahaan dan akhirnya kembali ke lokasi asal. Hasil yang ditampilkan yang terdiri atas:

Dikatakan di spek lokasi asal itu perusahaan. Namun, juga diminta untuk input ada terdapat lokasi yang menjadi titik asal. Maksudnya apa ya kak?

> Teknologi penyimpanan data (database) dibebaskan (tidak boleh menggunakan berkas txt, csv)
Data yang dimaksud disini apa saja ya kak?

**Comment by gilliantuerah** [comment]
> Dikatakan di spek lokasi asal itu perusahaan. Namun, juga diminta untuk input ada terdapat lokasi yang menjadi titik asal. Maksudnya apa ya kak?

Iya bener lokasi asal=perusahaan, dan harus tetap ada dalam jalur nantinya jadi koordinatnya juga harus diinput

> Data yang dimaksud disini apa saja ya kak?

Untuk data apa saja yang disimpan dibebaskan yaa, disesuaikan saja sama kebutuhannya.

**Comment by girvinjunod** [comment]
Halo kak mau bertanya lagi,
apakah ada format untuk input waktu pengiriman? Untuk kecepatan kurir dan estimasi waktu, apakah satuan untuk kecepatan dan jarak antar lokasi bebas?

**Comment by gilliantuerah** [comment]
- Untuk **waktu pengiriman** (HH:MM:SS) menggunakan sistem 24 jam ya
- Untuk **estimasi waktu** (x jam x menit x detik) dengan sistem 24 jam juga
- Untuk satuan **kecepatan** dan **jarak** dibebaskan

**Comment by girvinjunod** [comment]
Makasii kak atas jawabannya, 
Mau konfirmasi lagi, brarti kalau input waktunya dalam jam, untuk bonus yang memakai tanggal, apakah berarti memakai tanggal pengiriman dilakukan (tanggal now)

**Comment by gilliantuerah** [comment]
yes benerr

**Comment by girvinjunod** [comment]
Halo kak mau nanya lagi hehehe
Untuk spek bonus yg melakukan pencarian dari tanggal dan nama kurir, apakah informasi yg ditampilkan berupa semua data yg memenuhi syarat pencarian atau 1 saja?
